- name: Prep instaserver
  block:
  - stat:
      path: "{{ instaserver_extract_dir }}{{ instaserver_dir }}"
    register: instaserverextract
  - name: Extract instaserver
    command: sh {{ item.invocation.module_args.path }} -extract
    args:
      chdir: "{{ item.invocation.module_args.dest }}"
    when: instaserverextract.stat.exists == false
    #become: yes
    #become_user: "{{ epic_admin_user }}"
  #- name: Set instaserver directory owner
  #  ansible.builtin.file:
  #    path: "{{ instaserver_dir }}"
  #    owner: "{{ epic_admin_user }}"
  #    group: "{{ epic_admin_group }}"
  #    recurse: yes
  - name: show path for debug
    debug:
      msg: "{{ item.invocation.module_args.path }}"
  - stat: path="{{ item.invocation.module_args.path }}"
    register: instaserverfile
  - name: Move extracted instaserver contents to instaserver file directory
    command: "mv {{ instaserver_dir }} {{ instaserver_extract_dir }}"
    args:
      chdir: "{{ item.invocation.module_args.dest }}"
    when: instaserverfile.stat.exists != True